### ISSUE TITLE
issue with error handling preventing creation of new commands

### ISSUE THREAD

**Issue by modernNeo** [CSSS/wall_e#17]

**Comment by modernNeo** [comment]
@wnfldchen still giving me error

Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/mnt/c/Users/Jason Manshad/.local/lib/python3.5/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "main.py", line 165, in on_command_error
    print('Ignoring exception in command {}:'.format(ctx.command), file=sys.stderr)
AttributeError: 'MissingRequiredArgument' object has no attribute 'command'
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/mnt/c/Users/Jason Manshad/.local/lib/python3.5/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "main.py", line 165, in on_command_error
    print('Ignoring exception in command {}:'.format(ctx.command), file=sys.stderr)
AttributeError: 'MissingRequiredArgument' object has no attribute 'command'


with branch https://github.com/CSSS/wall_e/tree/adding_list_roles

**Comment by modernNeo** [comment]
was using improper discord pip module
