### ISSUE TITLE
fix issue with embed function

### ISSUE THREAD

**Issue by modernNeo** [CSSS/wall_e#259]
https://discordapp.com/channels/228761314644852736/478776321808269322/688155332987715627

```
2020-03-13 22:43:29 = INFO - [SFU sfu()] url for get request constructed: http://www.sfu.ca/bin/wcm/academic-calendar?2020/spring/courses/math/480w
2020-03-13 22:43:29 = INFO - [ManageCog on_command()] db_connection_string=[dbname='csss_discord_db' user='wall_e' host='PRODUCTION_MASTER_wall_e_db']
2020-03-13 22:43:29 = INFO - [ManageCog on_command()] PostgreSQL connection established
2020-03-13 22:43:29 = INFO - [ManageCog on_command()] sql_command=[INSERT INTO CommandStats ( epoch_time, YEAR, MONTH, DAY, HOUR, channel_name, Command, invoked_with, invoked_subcommand) VALUES (1584139409,2020 ,3,13,22 ,'bot-commands-and-misc', 'sfu','sfu','None');]
2020-03-13 22:43:29 = INFO - [SFU sfu()] get request successful
2020-03-13 22:43:29 = INFO - [SFU sfu()] parsing json data returned from get request
2020-03-13 22:43:29 = WARNING - Traceback (most recent call last):
2020-03-13 22:43:29 = WARNING -
2020-03-13 22:43:29 = WARNING -   File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 79, in wrapped
.    ret = await coro(*args, **kwargs)
2020-03-13 22:43:29 = WARNING -
2020-03-13 22:43:29 = WARNING -   File "/usr/src/app/resources/cogs/sfu.py", line 136, in sfu
.    footer=footer
2020-03-13 22:43:29 = WARNING -
2020-03-13 22:43:29 = WARNING -   File "/usr/src/app/resources/utilities/embed.py", line 71, in embed
.    "size of 1024".format(record[1], len(record[1] - 1024)))
2020-03-13 22:43:29 = WARNING -
2020-03-13 22:43:29 = WARNING - TypeError: unsupported operand type(s) for -: 'str' and 'int'
2020-03-13 22:43:29 = WARNING -
2020-03-13 22:43:29 = WARNING -
The above exception was the direct cause of the following exception:
2020-03-13 22:43:29 = WARNING -
2020-03-13 22:43:29 = WARNING - Traceback (most recent call last):
2020-03-13 22:43:29 = WARNING -
2020-03-13 22:43:29 = WARNING -   File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 863, in invoke
.    await ctx.command.invoke(ctx)
2020-03-13 22:43:29 = WARNING -
2020-03-13 22:43:29 = WARNING -   File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 728, in invoke
.    await injected(*ctx.args, **ctx.kwargs)
2020-03-13 22:43:29 = WARNING -
2020-03-13 22:43:29 = WARNING -   File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 88, in wrapped
.    raise CommandInvokeError(exc) from exc
2020-03-13 22:43:29 = WARNING -
2020-03-13 22:43:29 = WARNING - discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: unsupported operand type(s) for -: 'str' and 'int'
2020-03-13 22:43:29 = WARNING -
```

**Comment by modernNeo** [comment]
fixed with merging of pr 268
