### ISSUE TITLE
error in sfu.py

### ISSUE THREAD

**Issue by modernNeo** [CSSS/wall_e#456]
```
2023-11-06 12:19:29 = ERROR = wall_e = Traceback (most recent call last):
2023-11-06 12:19:29 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 235, in wrapped
.    ret = await coro(*args, **kwargs)
2023-11-06 12:19:29 = ERROR = wall_e =   File "/usr/src/app/extensions/sfu.py", line 430, in outline
.    room = f'{x["buildingCode"]} {x["roomNumber"]}'
2023-11-06 12:19:29 = ERROR = wall_e = KeyError: 'buildingCode'
2023-11-06 12:19:29 = ERROR = wall_e =
The above exception was the direct cause of the following exception:
2023-11-06 12:19:29 = ERROR = wall_e = Traceback (most recent call last):
2023-11-06 12:19:29 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1360, in invoke
.    await ctx.command.invoke(ctx)
2023-11-06 12:19:29 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1029, in invoke
.    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
2023-11-06 12:19:29 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 244, in wrapped
.    raise CommandInvokeError(exc) from exc
2023-11-06 12:19:29 = ERROR = wall_e = discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'buildingCode'
```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/wall_e/pull/452
