### ISSUE TITLE
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#467]
```
2023-11-15 21:51:32 = ERROR = wall_e = Traceback (most recent call last):

2023-11-15 21:51:32 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)

2023-11-15 21:51:32 = ERROR = wall_e =   File "/usr/src/app/extensions/ban.py", line 347, in ban
    await user.kick(reason=reason)

2023-11-15 21:51:32 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/member.py", line 762, in kick
    await self.guild.kick(self, reason=reason)

2023-11-15 21:51:32 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/guild.py", line 3661, in kick
    await self._state.http.kick(user.id, self.id, reason=reason)

2023-11-15 21:51:32 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 738, in request
    raise Forbidden(response, data)

2023-11-15 21:51:32 = ERROR = wall_e = discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2023-11-15 21:51:32 = ERROR = wall_e = 
The above exception was the direct cause of the following exception:


2023-11-15 21:51:32 = ERROR = wall_e = Traceback (most recent call last):

2023-11-15 21:51:32 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1360, in invoke
    await ctx.command.invoke(ctx)

2023-11-15 21:51:32 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore

2023-11-15 21:51:32 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc

2023-11-15 21:51:32 = ERROR = wall_e = discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions


```

**Comment by modernNeo** [comment]
happens when an account with higher perms than the bot is banned
