### ISSUE TITLE
KeyError: <UserPoint: UserPoint object (1)>


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#476]
```
2023-11-19 01:58:30 = ERROR = discord.ext.tasks = Unhandled exception in internal background task 'process_leveling_profile_data_for_lurkers'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 241, in _loop
    await self.coro(*args, **kwargs)
  File "/usr/src/app/extensions/leveling.py", line 443, in process_leveling_profile_data_for_lurkers
    await self.set_bucket_numbers()
  File "/usr/src/app/extensions/leveling.py", line 494, in set_bucket_numbers
    date_buckets[self.user_points[user_id]] += 1
KeyError: <UserPoint: UserPoint object (1)>

```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/wall_e/commit/224e8654f6b852fd0e99579cec1d67a1acb2de23
