### ISSUE TITLE
    line = f.readline()


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#490]
```
2024-01-14 18:23:06 = ERROR = discord.client = Attempting a reconnect in 1.18s
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 661, in connect
    await self.ws.poll_event()
  File "/usr/local/lib/python3.8/site-packages/discord/gateway.py", line 648, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
2024-01-14 18:23:10 = WARNING = discord.gateway = Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "./main.py", line 4, in <module>
    bot.run(wall_e_config.get_config_value("basic_config", "TOKEN"))
  File "/usr/src/app/utilities/wall_e_bot.py", line 43, in run
    super(WalleBot, self).run(
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 862, in run
    asyncio.run(runner())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/app/utilities/log_channel.py", line 32, in write_to_bot_log_channel
    line = f.readline()


```

**Comment by modernNeo** [comment]
server issues
