### ISSUE TITLE
TimeoutError: 


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#491]
```
2024-01-14 18:33:04 = ERROR = discord.client = Attempting a reconnect in 0.93s
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 661, in connect
    await self.ws.poll_event()
  File "/usr/local/lib/python3.8/site-packages/discord/gateway.py", line 648, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
2024-01-14 18:33:10 = WARNING = discord.gateway = Shard ID None heartbeat blocked for more than 110 seconds.
Loop thread traceback (most recent call last):
  File "./main.py", line 4, in <module>
    bot.run(wall_e_config.get_config_value("basic_config", "TOKEN"))
  File "/usr/src/app/utilities/wall_e_bot.py", line 43, in run
    super(WalleBot, self).run(
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 862, in run
    asyncio.run(runner())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 851, in runner
    await self.start(token, reconnect=reconnect)
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 780, in start
    await self.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 661, in connect
    await self.ws.poll_event()
  File "/usr/local/lib/python3.8/site-packages/discord/gateway.py", line 625, in poll_event
    await self.received_message(msg.data)
  File "/usr/local/lib/python3.8/site-packages/discord/gateway.py", line 500, in received_message
    msg = utils._from_json(msg)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)

Task exception was never retrieved
future: <Task finished name='Task-73' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-37' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-43' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-67' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-91' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-79' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-55' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-61' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-85' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-49' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-23' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-890' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-896' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-902' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-908' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-914' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 
Task exception was never retrieved
future: <Task finished name='Task-920' coro=<write_to_bot_log_channel() done, defined at /usr/src/app/utilities/log_channel.py:6> exception=Exception('[log_channel.py write_to_bot_log_channel()] write to channel failed\nTimeoutError: ')>
Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 45, in write_to_bot_log_channel
    await channel.send(output)
  File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/utilities/log_channel.py", line 63, in write_to_bot_log_channel
    raise Exception(
Exception: [log_channel.py write_to_bot_log_channel()] write to channel failed
TimeoutError: 

```

**Comment by modernNeo** [comment]
server issues
