### ISSUE TITLE
Exception: did not detect a ctx or interaction method


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#493]
```
2024-01-15 19:49:13 = ERROR = discord.client = Ignoring exception in on_member_join
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 443, in _run_event
    await coro(*args, **kwargs)
  File "/usr/src/app/extensions/ban.py", line 98, in watchdog
    e_obj = await embed(
  File "/usr/src/app/utilities/embed.py", line 102, in embed
    raise Exception("did not detect a ctx or interaction method")
Exception: did not detect a ctx or interaction method

```

**Comment by modernNeo** [comment]
fixed
