### ISSUE TITLE
TypeError: on_member_ban() takes 2 positional arguments but 3 were given


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#494]
```
2024-01-15 19:56:13 = ERROR = discord.client = Ignoring exception in on_member_ban
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 443, in _run_event
    await coro(*args, **kwargs)
  File "/usr/src/app/extensions/ban.py", line 273, in intercept
    e_obj = await embed(
  File "/usr/src/app/utilities/embed.py", line 102, in embed
    raise Exception("did not detect a ctx or interaction method")
Exception: did not detect a ctx or interaction method
2024-01-15 19:56:13 = ERROR = discord.client = Ignoring exception in on_member_ban
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 443, in _run_event
    await coro(*args, **kwargs)
TypeError: on_member_ban() takes 2 positional arguments but 3 were given

```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/wall_e/commit/b3031d18fb429516ccaefe0a2a756d88f1e03625
