### ISSUE TITLE
wall_e = discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Exception: did not detect a ctx or interaction method


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#495]
```
2024-01-15 21:53:53 = ERROR = wall_e = Traceback (most recent call last):

2024-01-15 21:53:53 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)

2024-01-15 21:53:53 = ERROR = wall_e =   File "/usr/src/app/extensions/ban.py", line 456, in convertbans
    e_obj = await embed(

2024-01-15 21:53:53 = ERROR = wall_e =   File "/usr/src/app/utilities/embed.py", line 104, in embed
    raise Exception("did not detect a ctx or interaction method")

2024-01-15 21:53:53 = ERROR = wall_e = Exception: did not detect a ctx or interaction method

2024-01-15 21:53:53 = ERROR = wall_e = 
The above exception was the direct cause of the following exception:


2024-01-15 21:53:53 = ERROR = wall_e = Traceback (most recent call last):

2024-01-15 21:53:53 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1360, in invoke
    await ctx.command.invoke(ctx)

2024-01-15 21:53:53 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore

2024-01-15 21:53:53 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc

2024-01-15 21:53:53 = ERROR = wall_e = discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Exception: did not detect a ctx or interaction method


```

**Comment by modernNeo** [comment]
fixed
