### ISSUE TITLE
TypeError: object of type 'Guild' has no len()


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#515]
```
2024-01-19 21:38:43 = ERROR = discord.client = Ignoring exception in on_member_ban
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 443, in _run_event
    await coro(*args, **kwargs)
  File "/usr/src/app/extensions/ban.py", line 216, in intercept
    await self.wall_e_ban(
  File "/usr/src/app/extensions/ban.py", line 331, in wall_e_ban
    e_obj = await embed(
  File "/usr/src/app/utilities/embed.py", line 168, in embed
    if len(footer_text) > 2048:
TypeError: object of type 'Guild' has no len()

```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/wall_e/commit/0ba263a8e3b6e011c6885aa081433e597a486317
