### ISSUE TITLE
wall_e = discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'ThreadMember' object has no attribute 'display_name'


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#517]
```
2024-01-31 11:07:56 = ERROR = wall_e = Traceback (most recent call last):

2024-01-31 11:07:56 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)

2024-01-31 11:07:56 = ERROR = wall_e =   File "/usr/src/app/extensions/here.py", line 126, in here
    embed = self.build_embed(members, channel)

2024-01-31 11:07:56 = ERROR = wall_e =   File "/usr/src/app/extensions/here.py", line 76, in build_embed
    nicks = "\n".join([member.display_name for member in members])

2024-01-31 11:07:56 = ERROR = wall_e =   File "/usr/src/app/extensions/here.py", line 76, in <listcomp>
    nicks = "\n".join([member.display_name for member in members])

2024-01-31 11:07:56 = ERROR = wall_e = AttributeError: 'ThreadMember' object has no attribute 'display_name'

2024-01-31 11:07:56 = ERROR = wall_e = 
The above exception was the direct cause of the following exception:


2024-01-31 11:07:56 = ERROR = wall_e = Traceback (most recent call last):

2024-01-31 11:07:56 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1360, in invoke
    await ctx.command.invoke(ctx)

2024-01-31 11:07:56 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore

2024-01-31 11:07:56 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc

2024-01-31 11:07:56 = ERROR = wall_e = discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'ThreadMember' object has no attribute 'display_name'


```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/wall_e/commit/a8b8f7252cd7d3a098fa059328ddc2b488b799b6
