### ISSUE TITLE
ModuleNotFoundError: No module named 'extensions.manage_test_guild'


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#523]
```
2024-02-15 23:23:19 = ERROR = discord.client = Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 443, in _run_event
    await coro(*args, **kwargs)
  File "/usr/src/app/overriden_coroutines/error_handlers.py", line 19, in report_text_command_error
    from extensions.manage_test_guild import ManageTestGuild
ModuleNotFoundError: No module named 'extensions.manage_test_guild'

```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/wall_e/commit/23a60f8887358da14900f7a88199438e894acb69
