### ISSUE TITLE
make sure logs printed to the log channel dont face this issue

### ISSUE THREAD

**Issue by modernNeo** [CSSS/wall_e#55]
2018-09-12 18:06:49 = WARNING - Task exception was never retrieved
future: <Task finished coro=<write_to_bot_log_channel() done, defined at ./main.py:84> exception=HTTPException('BAD REQUEST (status code: 400): Invalid Form Body\nIn content: Must be 2000 or fewer in length.',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "./main.py", line 104, in write_to_bot_log_channel
    await channel.send(line)
  File "/usr/local/lib/python3.5/site-packages/discord/abc.py", line 764, in send
    data = yield from state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/usr/local/lib/python3.5/site-packages/discord/http.py", line 216, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Invalid Form Body
In content: Must be 2000 or fewer in length.

**Comment by modernNeo** [comment]
being handled by PR https://github.com/CSSS/wall_e/pull/56
