### ISSUE TITLE
discord.app_commands.errors.CommandInvokeError: Command 'reset_user_bucket_numbers' raised an exception: InteractionResponded: This interaction has already been responded to before


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#571]
```
2024-03-28 19:14:06 = ERROR = Leveling = Encountered exception in command 'reset_user_bucket_numbers'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "/usr/src/app/extensions/leveling.py", line 678, in reset_user_bucket_numbers
    await interaction.response.send_message(embed=e_obj)
  File "/usr/local/lib/python3.8/site-packages/discord/interactions.py", line 777, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/usr/local/lib/python3.8/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/usr/local/lib/python3.8/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'reset_user_bucket_numbers' raised an exception: InteractionResponded: This interaction has already been responded to before

```

**Comment by modernNeo** [comment]
fixed
