### ISSUE TITLE
discord.errors.DiscordServerError: 503 Service Unavailable (error code: 0): upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: immediate connect error: No such file or directory


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#637]
```
2024-04-04 19:33:56 = ERROR = discord.ext.tasks = Unhandled exception in internal background task 'process_leveling_profile_data_for_lurkers'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 241, in _loop
    await self.coro(*args, **kwargs)
  File "/usr/src/app/extensions/leveling.py", line 509, in process_leveling_profile_data_for_lurkers
    member = await self.guild.fetch_member(user_id)
  File "/usr/local/lib/python3.8/site-packages/discord/guild.py", line 2330, in fetch_member
    data = await self._state.http.get_member(self.id, member_id)
  File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 742, in request
    raise DiscordServerError(response, data)
discord.errors.DiscordServerError: 503 Service Unavailable (error code: 0): upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: immediate connect error: No such file or directory

```

**Comment by modernNeo** [comment]
just a network hiccup

**Comment by modernNeo** [comment]
`process_leveling_profile_data_for_lurkers` need to be updated with a over-all try catch cause apparently the tasks.loops can stop indefinitely if one iteration of the loop errors out.

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/wall_e/commit/2b7a36c67cb4ae895a009f874fc9db90d55c299f
