### ISSUE TITLE
In content: Must be 4000 or fewer in length.


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#640]
```
2024-04-15 18:49:49 = ERROR = wall_e = Traceback (most recent call last):

2024-04-15 18:49:49 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)

2024-04-15 18:49:49 = ERROR = wall_e =   File "/usr/src/app/extensions/misc.py", line 343, in emojispeak
    await ctx.send(f"{ctx.author.mention} says {output}")

2024-04-15 18:49:49 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/context.py", line 1024, in send
    return await super().send(

2024-04-15 18:49:49 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/abc.py", line 1563, in send
    data = await state.http.send_message(channel.id, params=params)

2024-04-15 18:49:49 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)

2024-04-15 18:49:49 = ERROR = wall_e = discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 4000 or fewer in length.

2024-04-15 18:49:49 = ERROR = wall_e = 
The above exception was the direct cause of the following exception:


2024-04-15 18:49:49 = ERROR = wall_e = Traceback (most recent call last):

2024-04-15 18:49:49 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1360, in invoke
    await ctx.command.invoke(ctx)

2024-04-15 18:49:49 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore

2024-04-15 18:49:49 = ERROR = wall_e =   File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc

2024-04-15 18:49:49 = ERROR = wall_e = discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 4000 or fewer in length.


```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/wall_e/commit/275dca059b3bfcdb164b60b2f1613bacbdd911f1
