### ISSUE TITLE
discord.app_commands.errors.CommandInvokeError: Command 'roles_assignable' raised an exception: IndexError: string index out of range


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#642]
```
2024-04-21 15:18:13 = ERROR = RoleCommands = Encountered exception in command 'roles_assignable'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "/usr/src/app/extensions/role_commands.py", line 560, in roles
    await paginate_embed(
  File "/usr/src/app/utilities/paginate.py", line 59, in paginate_embed
    embed_obj = await imported_embed(
  File "/usr/src/app/utilities/embed.py", line 158, in embed
    if len(record[1]) > 1024:
IndexError: string index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/usr/local/lib/python3.8/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/usr/local/lib/python3.8/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'roles_assignable' raised an exception: IndexError: string index out of range

```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/wall_e/commit/1d31ed28b068b5d93fce4317db5b57ada7b891b2
