### ISSUE TITLE
AttributeError: 'User' object has no attribute 'roles'


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#646]
```
2024-06-06 20:01:24 = ERROR = discord.client = Ignoring exception in on_member_ban
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 443, in _run_event
    await coro(*args, **kwargs)
  File "/usr/src/app/extensions/ban.py", line 213, in intercept
    await self.wall_e_ban(
  File "/usr/src/app/extensions/ban.py", line 271, in wall_e_ban
    sorted_list_of_banner_user_roles = sorted(banned_user.roles, key=lambda x: int(x.position), reverse=True)
AttributeError: 'User' object has no attribute 'roles'

```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/wall_e/commit/ae0ee476eab491d3dcbcfb871d88637b046e2af3
