### ISSUE TITLE
discord.errors.DiscordServerError: 503 Service Unavailable (error code: 0): upstream connect error or disconnect/reset before headers. reset reason: connection termination


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#655]
```
2024-10-06 02:58:04 = ERROR = discord.ext.tasks = Unhandled exception in internal background task 'process_leveling_profile_data_for_lurkers'.
Traceback (most recent call last):
  File "/usr/src/app/extensions/leveling.py", line 510, in process_leveling_profile_data_for_lurkers
    member = await self.guild.fetch_member(user_id)
  File "/usr/local/lib/python3.9/site-packages/discord/guild.py", line 2365, in fetch_member
    data = await self._state.http.get_member(self.id, member_id)
  File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 754, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10007): Unknown Member

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 241, in _loop
    await self.coro(*args, **kwargs)
  File "/usr/src/app/extensions/leveling.py", line 512, in process_leveling_profile_data_for_lurkers
    member = await bot.fetch_user(user_id)
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 2564, in fetch_user
    data = await self.http.get_user(user_id)
  File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 756, in request
    raise DiscordServerError(response, data)
discord.errors.DiscordServerError: 503 Service Unavailable (error code: 0): upstream connect error or disconnect/reset before headers. reset reason: connection termination

```

**Comment by modernNeo** [comment]
hopefully fixed with https://github.com/CSSS/wall_e/commit/46ef7fd3dc27aa6c3d181613f306c47dee959363
