### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'fetch_member'


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#673]
```
2024-11-17 16:40:44 = ERROR = discord.ext.tasks = Unhandled exception in internal background task 'process_outdated_profile_pics'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 241, in _loop
    await self.coro(*args, **kwargs)
  File "/usr/src/app/extensions/leveling.py", line 677, in process_outdated_profile_pics
    await self._update_users(user_ids_to_update)
  File "/usr/src/app/extensions/leveling.py", line 633, in _update_users
    member = await self.guild.fetch_member(user_id)
AttributeError: 'NoneType' object has no attribute 'fetch_member'

```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/wall_e/commit/b6c1d6ea0c24d2e37f9a6dd046626eafe8bcba67
