### ISSUE TITLE
Exception: [wall_e_bot.py] Could not open log file to read from and sent entries to bot_log channel due to following error 'TextChannel' object is not iterable


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#674]
```
2024-11-24 10:02:45 = ERROR = discord.client = Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/src/app/utilities/wall_e_bot.py", line 187, in on_ready
    await self.bot_channel_manager.fix_text_channel_positioning(logger, guild=bot_guild)
  File "/usr/src/app/utilities/bot_channel_manager.py", line 296, in fix_text_channel_positioning
    for channel_under_category in channels_under_category:
TypeError: 'TextChannel' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/usr/src/app/utilities/wall_e_bot.py", line 190, in on_ready
    raise Exception(
Exception: [wall_e_bot.py] Could not open log file to read from and sent entries to bot_log channel due to following error 'TextChannel' object is not iterable

```

**Comment by modernNeo** [comment]
just testing in PROD
