### ISSUE TITLE
discord.errors.DiscordServerError: 503 Service Unavailable (error code: 0): upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: immediate connect error: No such file or directory


### ISSUE THREAD

**Issue by csss-admin** [CSSS/wall_e#675]
```
2024-11-26 16:29:55 = ERROR = discord.ext.tasks = Unhandled exception in internal background task 'process_outdated_profile_pics'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 241, in _loop
    await self.coro(*args, **kwargs)
  File "/usr/src/app/extensions/leveling.py", line 723, in process_outdated_profile_pics
    await self._update_users(self.update_outdated_profile_pics_logger, user_ids_to_update)
  File "/usr/src/app/extensions/leveling.py", line 666, in _update_users
    member = await self.guild.fetch_member(user_id)
  File "/usr/local/lib/python3.9/site-packages/discord/guild.py", line 2365, in fetch_member
    data = await self._state.http.get_member(self.id, member_id)
  File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 756, in request
    raise DiscordServerError(response, data)
discord.errors.DiscordServerError: 503 Service Unavailable (error code: 0): upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: immediate connect error: No such file or directory

```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/wall_e/commit/fc9930ec4ad4516742d9e8e7d5f4c156399fa531
